# Generated by Django 3.2 on 2021-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='jurusan',
            field=models.CharField(default='jurusan anda', max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
