# Generated by Django 3.2 on 2021-07-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='status',
            field=models.CharField(default='programer', max_length=100),
            preserve_default=False,
        ),
    ]
